# USD Explorer Application Template
# Template application for exploring and collaborating on large OpenUSD scenes

[metadata]
name = "omni_usd_explorer"
display_name = "USD Explorer"
type = "application"
category = "exploration"
description = "Template application for exploring and collaborating on large Open USD scenes"
version = "1.0.0"
author = "NVIDIA Omniverse"
license = "LicenseRef-NvidiaProprietary"

[metadata.compatibility]
platforms = ["linux-x86_64", "windows-x86_64"]
min_kit_version = "108.0.0"
languages = ["python"]

[metadata.tags]
tags = ["explorer", "collaboration", "usd", "large-scenes", "navigation"]

[template]
class = "ApplicationTemplate"
kit_file = "../../apps/usd_explorer/omni.usd_explorer.kit"
source_dir = "../../apps/usd_explorer"

requires_extensions = [
    {template = "omni_usd_explorer_setup", type = "setup"}
]

[variables]
application_name = "my_company.my_usd_explorer"
application_display_name = "My USD Explorer"
version = "0.1.0"

[documentation]
overview = """
USD Explorer is optimized for exploring and collaborating on large OpenUSD scenes.
It provides efficient navigation, collaboration tools, and performance optimizations
for working with complex 3D environments.
"""

use_cases = [
    "Exploring large USD scenes",
    "Collaborative scene review",
    "Performance-optimized USD navigation",
    "Scene analysis and inspection"
]

key_features = [
    "Optimized large scene handling",
    "Collaboration and annotation tools",
    "Advanced navigation controls",
    "Performance monitoring and analysis"
]

getting_started = """
1. Run: ./repo.sh template new omni_usd_explorer --name my_company.my_explorer
2. Configure the setup extension when prompted
3. Build: ./repo.sh build
4. Launch: ./repo.sh launch
"""

[dependencies]
required_extensions = []
optional_extensions = ["omni.kit.collaboration.bundle", "omni.kit.performance.profiler"]

[deployment]
supports_packaging = true
supports_containerization = true
supports_streaming = true
requires_display = true

[build]
requires_build = false
supports_debug = true
supports_release = true

[extensions]
[[extensions.setup]]
template = "omni_usd_explorer_setup"
required = true
description = "Setup extension for USD Explorer functionality"