# Example project configuration file
# Shows how to create a project-specific configuration

includes = ["base"]

[company]
name = "awesome_corp"
display_name = "Awesome Corporation"
domain = "awesomecorp.com"

[project]
name = "super_viewer"
display_name = "Super Viewer"
version = "1.0.0"
description = "An amazing USD viewer application"
author = "Awesome Team"

[application]
# Will resolve to: awesome_corp.super_viewer
name = "${company.name}.${project.name}"
# Will resolve to: Super Viewer
display_name = "${project.display_name}"
version = "${project.version}"

# Template-specific settings
[template]
type = "omni_usd_viewer"

# Extension overrides for USD Viewer template
[extensions.viewer_setup]
name = "${company.name}.${project.name}_setup"
display_name = "${project.display_name} Setup"
version = "${project.version}"

[extensions.viewer_messaging]
name = "${company.name}.${project.name}_messaging"
display_name = "${project.display_name} Messaging"
version = "${project.version}"

# Build settings
[build]
debug = true
release = true
verbose = false
jobs = 8

# Application-specific settings
[settings]
enable_rtx = true
default_scene = "omniverse://localhost/Projects/default.usd"
viewport_mode = "fill"