# Default Streaming Layer Template
# Application layer for Omniverse Kit App Streaming

[metadata]
name = "omni_default_streaming"
display_name = "Omniverse Kit App Streaming (Default)"
type = "component"
category = "streaming"
description = "Default streaming layer for Omniverse Kit applications, enables WebRTC streaming capabilities"
version = "1.0.0"
author = "NVIDIA Omniverse"
license = "LicenseRef-NvidiaProprietary"

[metadata.compatibility]
platforms = ["linux-x86_64", "windows-x86_64"]
min_kit_version = "108.0.0"
languages = ["configuration"]

[metadata.tags]
tags = ["streaming", "webrtc", "layer", "component", "remote"]

[template]
class = "ApplicationLayerTemplate"
source_dir = "../../apps/streaming_configs"
kit_file = "default_stream.kit"
layer_type = "streaming"

[variables]
version = "0.1.0"

[documentation]
overview = """
The Default Streaming Layer adds streaming capabilities to Kit applications,
enabling remote access and interaction through web browsers using WebRTC technology.
"""

use_cases = [
    "Remote application access",
    "Web-based 3D content streaming",
    "Cloud application deployment",
    "Multi-user collaborative sessions"
]

key_features = [
    "WebRTC streaming support",
    "Browser-compatible streaming",
    "Low-latency remote interaction",
    "Configurable streaming parameters"
]

[deployment]
supports_packaging = true
supports_containerization = true
requires_host_application = true

[build]
requires_build = false
supports_debug = true
supports_release = true

[integration]
requires_host_app = true
can_be_standalone = false
supported_app_types = ["application"]
component_type = "layer"
layer_type = "streaming"

[streaming]
protocol = "webrtc"
browser_compatible = true
requires_network = true
default_port = 8011