-- Standalone premake5.lua for test_standalone_fix
-- Generated by kit-app-template standalone generator

-- Configuration
BUILD_CONFIG = _OPTIONS["config"] or "release"
BUILD_DIR = "_build"

-- Root workspace
workspace "test_standalone_fix"
    configurations { "debug", "release" }
    platforms { "x86_64" }
    
    location(BUILD_DIR)
    
    -- Architecture
    architecture "x86_64"
    
    -- Configuration-specific settings
    filter "configurations:debug"
        defines { "DEBUG" }
        symbols "On"
        optimize "Off"
        
    filter "configurations:release"
        defines { "NDEBUG" }
        symbols "Off"
        optimize "On"
        
    filter {}

-- Include application/extension build if present
local app_premake = "source/apps/test_standalone_fix/premake5.lua"
if os.isfile(app_premake) then
    include(app_premake)
end

-- Print build information
print("Building standalone project: test_standalone_fix")
print("Configuration: " .. BUILD_CONFIG)
print("Build directory: " .. BUILD_DIR)
